/*
 * File: logger.c
 * Originally generated by GPT-5 (boilerplate implementation)
 * Modified and integrated by Mayukh Chakraborty.
*/

#include "logger.h"
#include <stdio.h>

void logger(logType name, char* title, char* message) {
    const char *BOLD   = "\033[1m";
    const char *RED    = "\033[31m";
    const char *YELLOW = "\033[33m";
    const char *BLUE   = "\033[34m";
    const char *WHITE  = "\033[97m";
    const char *RESET  = "\033[0m";

    const char *labelColor;
    const char *labelText;

    switch (name) {
        case ERROR:
            labelColor = RED;
            labelText = "ERROR";
            break;
        case WARNING:
            labelColor = YELLOW;
            labelText = "WARNING";
            break;
        case INFORMATION:
            labelColor = BLUE;
            labelText = "INFO";
            break;
        default:
            labelColor = WHITE;
            labelText = "LOG";
            break;
    }

    printf("%s%s[%s]%s %s%s%s\n",
        BOLD, labelColor, labelText, RESET,
        BOLD, WHITE, title);
    printf("%s", RESET);
    printf("%s\n", message);
    printf("%s", RESET); // safety reset
}